package dependency

import (
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"diffusion/internal/config"
	"diffusion/internal/galaxy"
	"diffusion/internal/role"

	"gopkg.in/yaml.v3"
)

// LockFileEntry represents a single dependency entry in the lock file
type LockFileEntry struct {
	Name            string            `yaml:"name"`
	Namespace       string            `yaml:"namespace,omitempty"` // Galaxy namespace (e.g., "community", "geerlingguy")
	Version         string            `yaml:"version"`
	ResolvedVersion string            `yaml:"resolved_version,omitempty"` // Actual version (e.g., "7.5.0" for ">=7.4.0")
	Type            string            `yaml:"type"`                       // "collection", "role", "tool"
	Hash            string            `yaml:"hash,omitempty"`
	PythonDeps      map[string]string `yaml:"python_deps,omitempty"` // Python dependencies with versions
	Src             string            `yaml:"src,omitempty"`         // Source URL for roles (git repo)
	Source          string            `yaml:"scm,omitempty"`         // SCM type for roles (git, hg, etc.)
}

// LockFile represents the diffusion.lock file structure
type LockFile struct {
	Version     string                `yaml:"version"`     // Lock file format version
	Generated   string                `yaml:"generated"`   // Timestamp
	Hash        string                `yaml:"hash"`        // Overall dependency hash
	Python      *config.PythonVersion `yaml:"python"`      // Python version info
	Collections []LockFileEntry       `yaml:"collections"` // Locked collections
	Roles       []LockFileEntry       `yaml:"roles"`       // Locked roles
	Tools       []LockFileEntry       `yaml:"tools"`       // Locked tools (ansible, molecule, etc.)
}

const (
	LockFileVersion = "1.0"
)

// LoadLockFile loads the diffusion.lock file
func LoadLockFile() (*LockFile, error) {
	data, err := os.ReadFile(config.LockFileName)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil // Lock file doesn't exist yet
		}
		return nil, fmt.Errorf("failed to read lock file: %w", err)
	}

	var lockFile LockFile
	if err := yaml.Unmarshal(data, &lockFile); err != nil {
		return nil, fmt.Errorf("failed to parse lock file: %w", err)
	}

	return &lockFile, nil
}

// SaveLockFile saves the lock file
func SaveLockFile(lockFile *LockFile) error {
	lockFile.Version = LockFileVersion
	lockFile.Generated = time.Now().UTC().Format(time.RFC3339)

	data, err := yaml.Marshal(lockFile)
	if err != nil {
		return fmt.Errorf("failed to marshal lock file: %w", err)
	}

	// Add header comment
	header := fmt.Sprintf("# This file is automatically generated by diffusion.\n# Do not edit this file manually.\n# Generated: %s\n\n", lockFile.Generated)
	data = append([]byte(header), data...)

	if err := os.WriteFile(config.LockFileName, data, 0644); err != nil {
		return fmt.Errorf("failed to write lock file: %w", err)
	}

	return nil
}

// GenerateLockFile generates a new lock file from current dependencies with resolved versions
func GenerateLockFile(collections []config.CollectionRequirement, roles []config.RoleRequirement, toolVersions map[string]string, pythonVersion *config.PythonVersion) (*LockFile, error) {
	lockFile := &LockFile{
		Version:     LockFileVersion,
		Python:      pythonVersion,
		Collections: make([]LockFileEntry, 0),
		Roles:       make([]LockFileEntry, 0),
		Tools:       make([]LockFileEntry, 0),
	}

	galaxyAPI := galaxy.NewGalaxyAPI()

	// Add collections with resolved versions
	for _, col := range collections {
		if col.Source == "" {
			col.Source = "galaxy"
		}
		entry := LockFileEntry{
			Name:      col.Name,
			Namespace: col.Namespace,
			Version:   col.Version,
			Type:      "collection",
			Source:    col.Source,
			Src:       col.SourceURL,
		}

		if col.Source != "galaxy" {
			// For non-Galaxy sources we are trying to resolve from git
			if col.SourceURL == "" {
				log.Printf("Skipping collection %s: missing source URL for non-Galaxy source %s", col.Name, col.Source)
				continue
			}

			resolvedVersion, err := galaxy.ResolveVersionFromGit(col.SourceURL, col.Version)
			if err != nil {
				log.Printf("Failed to resolve version for collection %s from git: %v", col.Name, err)
				// Use the version constraint if resolution fails
				if col.Version != "" && col.Version != "latest" {
					entry.ResolvedVersion = col.Version
				} else {
					entry.ResolvedVersion = "main"
				}
			} else {
				entry.ResolvedVersion = resolvedVersion
			}
		} else {
			// Resolve version from Galaxy using Namespace field
			// Collection Name in config is "scenario.collectionname", Namespace is separate
			namespace := col.Namespace
			collectionName := col.Name

			// Strip scenario prefix from collection name for Galaxy resolution
			if parts := strings.SplitN(collectionName, ".", 2); len(parts) == 2 {
				collectionName = parts[1]
			}

			resolvedVersion, err := galaxyAPI.ResolveVersion(namespace, collectionName, "collection", col.Version)
			if err != nil {
				// Display as namespace.name for clarity in warning
				displayName := col.Name
				if namespace != "" {
					displayName = namespace + "." + collectionName
				}
				fmt.Printf("Warning: Failed to resolve version for %s: %v\n", displayName, err)
				// Use the version constraint if resolution fails
				if col.Version != "" && col.Version != "latest" {
					entry.ResolvedVersion = col.Version
				} else {
					entry.ResolvedVersion = "latest"
				}
			} else {
				entry.ResolvedVersion = resolvedVersion
			}
		}

		// Get Python dependencies for this collection
		// Use namespace.name format for lookup (e.g., "community.general")
		pythonDepsKey := col.Name
		if col.Namespace != "" {
			// Strip scenario prefix and reconstruct as namespace.name
			colName := col.Name
			if parts := strings.SplitN(colName, ".", 2); len(parts) == 2 {
				colName = parts[1]
			}
			pythonDepsKey = col.Namespace + "." + colName
		}
		pythonDeps := getCollectionPythonDependencies(pythonDepsKey)
		if len(pythonDeps) > 0 {
			// Resolve Python package versions
			resolved, err := galaxy.ResolvePythonDependencies(pythonDeps)
			if err != nil {
				fmt.Printf("Warning: Failed to resolve Python deps for %s: %v\n", col.Name, err)
			} else {
				entry.PythonDeps = resolved
			}
		}

		lockFile.Collections = append(lockFile.Collections, entry)
	}

	// Add roles with resolved versions
	for _, role := range roles {
		if role.Scm == "" {
			role.Scm = "git"
		}

		entry := LockFileEntry{
			Name:      role.Name,
			Namespace: role.Namespace,
			Version:   role.Version, // This is the constraint from diffusion.toml
			Type:      "role",
			Src:       role.Src, // Store git URL
			Source:    role.Scm, // Store SCM type (git, hg, etc.) - yaml tag is "scm"
		}

		// Determine resolution strategy based on source
		resolved := false

		maxAttempts := 3

		for attempt := range maxAttempts {
			// Priority 1: If git URL is provided, resolve from git
			if role.Src != "" && (strings.Contains(role.Src, "github.com") || strings.Contains(role.Src, "gitlab.com") || strings.HasSuffix(role.Src, ".git")) {
				resolvedVersion, err := galaxy.ResolveVersionFromGit(role.Src, role.Version)
				if err != nil {
					fmt.Printf("Warning: Failed to resolve version for role %s from git (attempt %d/%d): %v\n", role.Name, attempt+1, maxAttempts, err)
				} else {
					entry.ResolvedVersion = resolvedVersion
					resolved = true
				}
			}

			// Priority 2: If not resolved and has Namespace, try Galaxy API
			if !resolved && role.Namespace != "" && role.Scm != "git" {
				// Role Name in config is "scenario.rolename", Namespace is separate
				roleName := fmt.Sprintf("%s.%s", role.Namespace, role.Name)
				// Strip scenario prefix for Galaxy resolution
				if parts := strings.SplitN(roleName, ".", 2); len(parts) == 2 {
					roleName = parts[1]
				}
				resolvedVersion, err := galaxyAPI.ResolveRoleVersion(role.Namespace, roleName, role.Version)
				if err != nil {
					fmt.Printf("Warning: Failed to resolve version for role %s from Galaxy (attempt %d/%d): %v\n", role.Name, attempt+1, maxAttempts, err)
				} else {
					entry.ResolvedVersion = resolvedVersion
					resolved = true
				}
			}

			if resolved {
				break
			}

			// Wait before retrying (exponential backoff)
			if attempt < maxAttempts-1 {
				backoff := time.Duration(1<<uint(attempt)) * time.Second
				fmt.Printf("Retrying role %s in %v...\n", role.Name, backoff)
				time.Sleep(backoff)
			}
		}

		// Fallback: Use constraint or default to "main"
		if !resolved {
			if entry.ResolvedVersion == "" || entry.ResolvedVersion == "latest" || entry.ResolvedVersion == "main" {
				entry.ResolvedVersion = "main"
			} else {
				// Use the version constraint as resolved version
				entry.ResolvedVersion = role.Version
			}
		}

		lockFile.Roles = append(lockFile.Roles, entry)
	}

	// Add tools with resolved Python package versions
	toolPackages := []string{}
	for tool, version := range toolVersions {
		entry := LockFileEntry{
			Name:    tool,
			Version: version,
			Type:    "tool",
			Source:  "pypi",
		}

		// Format as Python package
		pkgName := formatDependency(tool, version)
		toolPackages = append(toolPackages, pkgName)

		lockFile.Tools = append(lockFile.Tools, entry)
	}

	// Resolve all tool versions from PyPI
	if len(toolPackages) > 0 {
		resolved, err := galaxy.ResolvePythonDependencies(toolPackages)
		if err != nil {
			fmt.Printf("Warning: Failed to resolve tool versions: %v\n", err)
		} else {
			// Update tool entries with resolved versions
			for i := range lockFile.Tools {
				if resolvedVer, ok := resolved[lockFile.Tools[i].Name]; ok {
					lockFile.Tools[i].ResolvedVersion = resolvedVer
				}
			}
		}
	}

	// Compute overall hash
	lockFile.Hash = ComputeDependencyHash(collections, roles, toolVersions, pythonVersion)

	return lockFile, nil
}

// ValidateLockFile validates if the lock file is up-to-date
func ValidateLockFile(lockFile *LockFile, collections []config.CollectionRequirement, roles []config.RoleRequirement, toolVersions map[string]string, pythonVersion *config.PythonVersion) (bool, error) {
	if lockFile == nil {
		return false, nil
	}
	currentHash := ComputeDependencyHash(collections, roles, toolVersions, pythonVersion)
	return lockFile.Hash == currentHash, nil
}

// UpdateLockFile updates the lock file with current dependencies
func UpdateLockFile() error {
	// Load current configuration
	depConfig, err := LoadDependencyConfig()
	if err != nil {
		return fmt.Errorf("failed to load dependency config: %w", err)
	}

	// Convert depConfig to resolver format
	// Collections: use directly from depConfig
	collections := depConfig.Collections
	if collections == nil {
		collections = []config.CollectionRequirement{}
	}

	// Roles: use directly from depConfig (already normalized in LoadDependencyConfig)
	roles := depConfig.Roles
	if roles == nil {
		roles = []config.RoleRequirement{}
	}

	// Python version
	pythonVersion := depConfig.Python
	if pythonVersion == nil {
		pythonVersion = &config.PythonVersion{
			Min:    config.DefaultMinPythonVersion,
			Max:    config.DefaultMaxPythonVersion,
			Pinned: config.PinnedPythonVersion,
		}
	}

	// Tool versions
	toolVersions := map[string]string{
		"ansible":      depConfig.Ansible,
		"molecule":     depConfig.Molecule,
		"ansible-lint": depConfig.AnsibleLint,
		"yamllint":     depConfig.YamlLint,
	}

	// Set defaults for empty tool versions
	if toolVersions["ansible"] == "" {
		toolVersions["ansible"] = config.DefaultAnsibleVersion
	}
	if toolVersions["molecule"] == "" {
		toolVersions["molecule"] = config.DefaultMoleculeVersion
	}
	if toolVersions["ansible-lint"] == "" {
		toolVersions["ansible-lint"] = config.DefaultAnsibleLintVersion
	}
	if toolVersions["yamllint"] == "" {
		toolVersions["yamllint"] = config.DefaultYamlLintVersion
	}

	// Generate and save lock file
	lockFile, err := GenerateLockFile(collections, roles, toolVersions, pythonVersion)
	if err != nil {
		return fmt.Errorf("failed to generate lock file: %w", err)
	}

	if err := SaveLockFile(lockFile); err != nil {
		return fmt.Errorf("failed to save lock file: %w", err)
	}

	return nil
}

// CheckLockFileStatus checks if YAML manifests (requirements.yml, meta.yml)
// are in sync with the lock file. It compares names and resolved versions.
func CheckLockFileStatus() (bool, error) {
	lockFile, err := LoadLockFile()
	if err != nil {
		return false, err
	}

	if lockFile == nil {
		return false, nil // No lock file exists
	}

	// Discover scenarios from scenarios/ directory
	scenarios := []string{}
	scenariosDir := "scenarios"
	if info, err := os.Stat(scenariosDir); err == nil && info.IsDir() {
		entries, err := os.ReadDir(scenariosDir)
		if err == nil {
			for _, entry := range entries {
				if entry.IsDir() {
					scenarios = append(scenarios, entry.Name())
				}
			}
		}
	}
	if len(scenarios) == 0 {
		scenarios = append(scenarios, "default")
	}

	// Check requirements.yml for each scenario
	for _, scenario := range scenarios {
		_, req, err := role.LoadRoleConfig(scenario)
		if err != nil {
			return false, fmt.Errorf("failed to load role config for scenario %s: %w", scenario, err)
		}

		// Build expected collections from lock file for this scenario
		// Lock file: Name="default.general", Namespace="community", ResolvedVersion="9.0.0"
		// YAML after sync: Name="community.general", Version="9.0.0"
		prefix := scenario + "."
		expectedCols := map[string]string{} // yamlName -> resolvedVersion
		for _, col := range lockFile.Collections {
			if !strings.HasPrefix(col.Name, prefix) {
				continue
			}
			colName := strings.TrimPrefix(col.Name, prefix)
			yamlName := colName
			if col.Namespace != "" {
				yamlName = col.Namespace + "." + colName
			}
			version := col.ResolvedVersion
			if version == "" {
				version = col.Version
			}
			expectedCols[yamlName] = version
		}

		// Compare collections
		if len(req.Collections) != len(expectedCols) {
			return false, nil
		}
		for _, col := range req.Collections {
			expected, ok := expectedCols[col.Name]
			if !ok {
				return false, nil
			}
			if col.Version != expected {
				return false, nil
			}
		}

		// Build expected roles from lock file for this scenario
		// Lock file: Name="default.docker", Namespace="geerlingguy", ResolvedVersion="7.4.1"
		// YAML after sync: Name="geerlingguy.docker" (galaxy) or Name="rolename" with Src (git), Version="7.4.1"
		expectedRoles := map[string]string{} // yamlName -> resolvedVersion
		for _, lockRole := range lockFile.Roles {
			if !strings.HasPrefix(lockRole.Name, prefix) {
				continue
			}
			roleName := strings.TrimPrefix(lockRole.Name, prefix)
			yamlRoleName := roleName
			if lockRole.Namespace != "" && lockRole.Src == "" {
				yamlRoleName = lockRole.Namespace + "." + roleName
			}
			version := lockRole.ResolvedVersion
			if version == "" {
				version = lockRole.Version
			}
			if version == "" || version == "latest" {
				version = "main"
			}
			expectedRoles[yamlRoleName] = version
		}

		// Compare roles
		if len(req.Roles) != len(expectedRoles) {
			return false, nil
		}
		for _, r := range req.Roles {
			expected, ok := expectedRoles[r.Name]
			if !ok {
				return false, nil
			}
			if r.Version != expected {
				return false, nil
			}
		}
	}

	// Check meta.yml — only default scenario collections
	meta, _, err := role.LoadRoleConfig("")
	if err != nil {
		return false, fmt.Errorf("failed to load meta config: %w", err)
	}

	// Build expected meta collections from lock file (default scenario only, namespace.name, no versions)
	defaultPrefix := "default."
	expectedMeta := map[string]bool{}
	for _, col := range lockFile.Collections {
		if !strings.HasPrefix(col.Name, defaultPrefix) {
			continue
		}
		colName := strings.TrimPrefix(col.Name, defaultPrefix)
		metaName := colName
		if col.Namespace != "" {
			metaName = col.Namespace + "." + colName
		}
		expectedMeta[metaName] = true
	}

	if len(meta.Collections) != len(expectedMeta) {
		return false, nil
	}
	for _, metaCol := range meta.Collections {
		// meta.yml entries may have version constraints appended (e.g., "community.general>=7.4.0")
		// Strip the version part to get just the name
		metaName := metaCol
		for _, op := range []string{">=", "<=", "==", "!=", ">", "<"} {
			if idx := strings.Index(metaName, op); idx > 0 {
				metaName = metaName[:idx]
				break
			}
		}
		if !expectedMeta[metaName] {
			return false, nil
		}
	}

	return true, nil
}
