---
name: 'Diffusion Molecule Test'
description: 'Run Molecule tests for Ansible roles using Diffusion'
author: 'Polar-Team'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  diffusion-version:
    description: 'Diffusion version to use (e.g., latest, v0.3.13)'
    required: false
    default: 'latest'
  run-lint:
    description: 'Run lint tests'
    required: false
    default: 'true'
  run-verify:
    description: 'Run verify tests'
    required: false
    default: 'true'
  run-idempotence:
    description: 'Run idempotence tests'
    required: false
    default: 'true'
  run-converge:
    description: 'Run converge (always runs before other tests)'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for the role'
    required: false
    default: '.'
  cache-enabled:
    description: 'Enable caching for Ansible roles, collections, and optionally UV/Docker'
    required: false
    default: 'false'
  cache-uv:
    description: 'Cache UV/Python packages (requires cache-enabled: true)'
    required: false
    default: 'false'
  cache-docker:
    description: 'Cache DinD Docker images as tarballs (requires cache-enabled: true)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Install SLSA verifier
      shell: bash
      run: |
        SLSA_VERSION="v2.7.0"
        wget -qO /tmp/slsa-verifier "https://github.com/slsa-framework/slsa-verifier/releases/download/${SLSA_VERSION}/slsa-verifier-linux-amd64"
        chmod +x /tmp/slsa-verifier
        sudo mv /tmp/slsa-verifier /usr/local/bin/slsa-verifier

    - name: Download Diffusion
      shell: bash
      run: |
        if [ "${{ inputs.diffusion-version }}" = "latest" ]; then
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/Polar-Team/diffusion/releases/latest | jq -r .tag_name)
        else
          LATEST_RELEASE="${{ inputs.diffusion-version }}"
        fi
        echo "DIFFUSION_RELEASE=${LATEST_RELEASE}" >> "$GITHUB_ENV"

        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          ARCHIVE_NAME="diffusion-linux-amd64.tar.gz"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCHIVE_NAME="diffusion-linux-arm64.tar.gz"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        echo "DIFFUSION_ARCHIVE=${ARCHIVE_NAME}" >> "$GITHUB_ENV"

        BASE_URL="https://github.com/Polar-Team/diffusion/releases/download/${LATEST_RELEASE}"
        echo "Downloading Diffusion ${LATEST_RELEASE} (${ARCHIVE_NAME})..."
        wget -qO /tmp/diffusion.tar.gz        "${BASE_URL}/${ARCHIVE_NAME}"
        wget -qO /tmp/diffusion.tar.gz.sig    "${BASE_URL}/${ARCHIVE_NAME}.sig"
        wget -qO /tmp/diffusion.tar.gz.pem    "${BASE_URL}/${ARCHIVE_NAME}.pem"
        wget -qO /tmp/SHA256SUMS              "${BASE_URL}/SHA256SUMS"
        wget -qO /tmp/multiple.intoto.jsonl   "${BASE_URL}/multiple.intoto.jsonl"

    - name: Verify SHA256 checksum
      shell: bash
      run: |
        cd /tmp
        grep "${DIFFUSION_ARCHIVE}" SHA256SUMS | sha256sum --check --ignore-missing
        echo "Checksum verified."

    - name: Verify Cosign signature
      shell: bash
      run: |
        cosign verify-blob \
          --certificate /tmp/diffusion.tar.gz.pem \
          --signature /tmp/diffusion.tar.gz.sig \
          --certificate-identity-regexp="https://github.com/Polar-Team/diffusion" \
          --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
          /tmp/diffusion.tar.gz
        echo "Cosign signature verified."

    - name: Verify SLSA provenance
      shell: bash
      run: |
        slsa-verifier verify-artifact /tmp/diffusion.tar.gz \
          --provenance-path /tmp/multiple.intoto.jsonl \
          --source-uri github.com/Polar-Team/diffusion \
          --source-tag "${DIFFUSION_RELEASE}"
        echo "SLSA provenance verified."

    - name: Install Diffusion
      shell: bash
      run: |
        echo "Extracting archive..."
        tar -xzf /tmp/diffusion.tar.gz -C /tmp
        chmod +x /tmp/diffusion
        sudo mv /tmp/diffusion /usr/local/bin/diffusion
        rm /tmp/diffusion.tar.gz /tmp/diffusion.tar.gz.sig /tmp/diffusion.tar.gz.pem \
           /tmp/SHA256SUMS /tmp/multiple.intoto.jsonl

        echo "Verifying installation..."
        diffusion version

    # --- Cache setup ---
    - name: Configure Diffusion cache
      if: inputs.cache-enabled == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Configuring Diffusion cache"
        CACHE_FLAGS=""
        if [ "${{ inputs.cache-uv }}" = "true" ]; then
          CACHE_FLAGS="${CACHE_FLAGS} --uv"
        fi
        if [ "${{ inputs.cache-docker }}" = "true" ]; then
          CACHE_FLAGS="${CACHE_FLAGS} --docker"
        fi
        diffusion cache enable${CACHE_FLAGS}
        echo "Cache configured:"
        diffusion cache status
        echo "::endgroup::"

    - name: Compute cache key
      if: inputs.cache-enabled == 'true'
      id: cache-key
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Build a hash from dependency-relevant files
        HASH_INPUT=""
        if [ -f diffusion.toml ]; then
          HASH_INPUT="${HASH_INPUT}$(cat diffusion.toml)"
        fi
        if [ -f requirements.yml ]; then
          HASH_INPUT="${HASH_INPUT}$(cat requirements.yml)"
        fi
        if [ -f diffusion.lock ]; then
          HASH_INPUT="${HASH_INPUT}$(cat diffusion.lock)"
        fi
        FILE_HASH=$(echo -n "${HASH_INPUT}" | sha256sum | cut -d' ' -f1)
        echo "hash=${FILE_HASH}" >> "$GITHUB_OUTPUT"

        # Read cache_id from diffusion.toml for the cache path
        CACHE_ID=$(grep -E '^\s*cache_id\s*=' diffusion.toml | sed 's/.*=\s*"\(.*\)"/\1/' | tr -d ' ')
        echo "cache-id=${CACHE_ID}" >> "$GITHUB_OUTPUT"

    - name: Restore Diffusion cache
      if: inputs.cache-enabled == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.diffusion/cache
        key: diffusion-cache-${{ steps.cache-key.outputs.hash }}
        restore-keys: |
          diffusion-cache-

    - name: Run converge
      if: inputs.run-converge == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Running molecule converge"
        diffusion molecule --ci
        echo "::endgroup::"

    - name: Run lint
      if: inputs.run-lint == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Running molecule lint"
        diffusion molecule --ci --lint
        echo "::endgroup::"

    - name: Run verify
      if: inputs.run-verify == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Running molecule verify"
        diffusion molecule --ci --verify
        echo "::endgroup::"

    - name: Run idempotence
      if: inputs.run-idempotence == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Running molecule idempotence"
        diffusion molecule --ci --idempotence
        echo "::endgroup::"

    - name: Cleanup
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Cleaning up"
        diffusion molecule --ci --wipe || true
        echo "::endgroup::"

    - name: Show cache status
      if: always() && inputs.cache-enabled == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Cache status after run"
        diffusion cache status || true
        echo "::endgroup::"
