---
# Example: Testing Multiple Roles in a Monorepo
# This example shows how to test multiple roles in the same repository

name: Multi-Role Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-role1:
    name: Test Role 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Diffusion Tests
        uses: Polar-Team/diffusion/diffusion-test@main
        with:
          diffusion-version: 'latest'
          working-directory: 'roles/role1'
          run-lint: 'true'
          run-verify: 'true'
          run-idempotence: 'true'

  test-role2:
    name: Test Role 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Diffusion Tests
        uses: Polar-Team/diffusion/diffusion-test@main
        with:
          diffusion-version: 'latest'
          working-directory: 'roles/role2'
          run-lint: 'true'
          run-verify: 'true'
          run-idempotence: 'true'
