package deploy

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"log"
	"os"
	"strings"

	"diffusion/internal/config"
	"diffusion/internal/dependency"
	"diffusion/internal/utils"
)

// generateSessionID returns a random UUIDv4 string for unique container naming.
func generateSessionID() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		// Fallback: use timestamp-based ID if crypto/rand fails (should never happen).
		return fmt.Sprintf("%x", b)
	}
	// Set version (4) and variant (RFC 4122) bits.
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// ResolvedCredential is a flattened artifact credential ready to be injected
// into the container environment.
type ResolvedCredential struct {
	Name     string
	URL      string
	Username string
	Password string
	Token    string
}

// DeployContainerConfig holds everything needed to spin up the molecule
// container in "deploy mode". Roles and collections are installed INSIDE the
// container from a requirements.yml — there are no host-side download paths.
type DeployContainerConfig struct {
	// MergedLock drives the Python version, Ansible version, and pyproject.toml.
	MergedLock *dependency.LockFile

	// InventoryPath is the absolute host-side path to the generated YAML inventory.
	InventoryPath string

	// PlaybookDir is the host-side directory mounted read-only at /deploy/playbook/.
	// It must contain:
	//   wrapper.yml        — the generated wrapper playbook
	//   <playbook>.yml     — the user or auto-generated target playbook
	//   requirements.yml   — galaxy install manifest
	PlaybookDir string

	// ExtraVarsFile is an optional host-side JSON file mounted at /deploy/extra_vars.json.
	ExtraVarsFile string

	// SSHKeys is a map of hostname (or "*" for all) → base64-encoded SSH private
	// key. Passed as env vars into the container, decoded at runtime to
	// /tmp/ssh-keys/<host>, and set as ansible_ssh_private_key_file in the inventory.
	SSHKeys map[string]string

	// ContainerRegistry configures the molecule container image.
	ContainerRegistry *config.ContainerRegistry

	// ArtifactSources holds resolved credentials forwarded as env vars.
	ArtifactSources []ResolvedCredential

	// VaultToken and VaultAddr are forwarded when set (override env vars).
	VaultToken string
	VaultAddr  string
}

// containerRolesPath and containerCollectionsPath are the install targets used
// inside the container. ansible-galaxy writes here; ansible-playbook reads here.
const (
	containerRolesPath       = "/tmp/diffusion/roles"
	containerCollectionsPath = "/tmp/diffusion/collections"
)

// RunDeployContainer starts the molecule container in deploy mode.
// The container:
//  1. Installs roles + collections from /deploy/playbook/requirements.yml
//     into in-container /tmp/diffusion/{roles,collections}.
//  2. Runs ansible-playbook with the wrapper playbook.
//
// Nothing is written to the host file system for dependencies — the container
// is ephemeral and discarded on exit (--rm).
func RunDeployContainer(cfg DeployContainerConfig) error {
	image := utils.GetImageURL(cfg.ContainerRegistry)
	log.Printf(config.ColorGreen+"Using container image: %s"+config.ColorReset, image)

	sessionID := generateSessionID()

	args, err := buildDeployDockerArgs(cfg, image)
	if err != nil {
		return fmt.Errorf("failed to build docker args: %w", err)
	}

	log.Printf(config.ColorGreen + "Starting deploy container (roles/collections will be installed inside)..." + config.ColorReset)

	return utils.DockerRunDeployContainer(sessionID, args)
}

// buildDeployDockerArgs constructs the full `docker run` argument list.
//
// The container entrypoint is overridden to a shell one-liner that:
//
//	a) installs roles + collections from requirements.yml into /tmp/diffusion/
//	b) runs ansible-playbook with those paths set via ANSIBLE_* env vars
func buildDeployDockerArgs(cfg DeployContainerConfig, image string) ([]string, error) {
	var args []string

	// --- Volume mounts (read-only; host paths → container paths) ---

	// Inventory
	args = append(args, "-v", fmt.Sprintf("%s:/deploy/inventory.yml:ro", cfg.InventoryPath))

	// Playbook directory: wrapper.yml + target playbook + requirements.yml
	args = append(args, "-v", fmt.Sprintf("%s:/deploy/playbook:ro", cfg.PlaybookDir))

	// SSH keys (needed for Ansible SSH connections to target hosts)
	if sshDir := sshKeyDir(); sshDir != "" {
		args = append(args, "-v", fmt.Sprintf("%s:/root/.ssh:ro", sshDir))
	}

	// Pass base64 SSH keys as env vars (decoded inside container, no mount needed).
	for host, keyB64 := range cfg.SSHKeys {
		envName := "SSH_KEY_" + strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(host))
		args = append(args, "-e", envName+"="+keyB64)
	}

	// Mount additional SSH key directories referenced in the inventory
	// (handles keys outside ~/.ssh, e.g. project-local keys generated by Terraform).
	extraDirs := extractSSHKeyDirs(cfg.InventoryPath)
	for i, dir := range extraDirs {
		containerPath := fmt.Sprintf("/deploy/ssh-keys-%d", i)
		args = append(args, "-v", fmt.Sprintf("%s:%s:ro", dir, containerPath))
	}

	// Extra vars (optional)
	if cfg.ExtraVarsFile != "" {
		args = append(args, "-v", fmt.Sprintf("%s:/deploy/extra_vars.json:ro", cfg.ExtraVarsFile))
	}

	// --- Environment variables ---

	args = append(args,
		"-e", "UV_VENV_CLEAR=1",
		"-e", "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
		// Tell Ansible where the in-container installs will land.
		"-e", fmt.Sprintf("ANSIBLE_ROLES_PATH=%s", containerRolesPath),
		"-e", fmt.Sprintf("ANSIBLE_COLLECTIONS_PATH=%s", containerCollectionsPath),
	)

	// Vault
	vaultToken := cfg.VaultToken
	if vaultToken == "" {
		vaultToken = os.Getenv("VAULT_TOKEN")
	}
	vaultAddr := cfg.VaultAddr
	if vaultAddr == "" {
		vaultAddr = os.Getenv("VAULT_ADDR")
	}
	args = append(args,
		"-e", "VAULT_TOKEN="+vaultToken,
		"-e", "VAULT_ADDR="+vaultAddr,
	)

	// Python version from merged lock
	pythonVer := config.PinnedPythonVersion
	if cfg.MergedLock != nil && cfg.MergedLock.Python != nil && cfg.MergedLock.Python.Pinned != "" {
		pythonVer = cfg.MergedLock.Python.Pinned
	}
	args = append(args, "-e", "PYTHON_PINNED_VERSION="+pythonVer)

	// pyproject.toml from merged lock (Ansible + tool versions)
	if cfg.MergedLock != nil {
		if content, err := buildPyprojectFromLock(cfg.MergedLock); err == nil {
			args = append(args, "-e",
				"PYPROJECT_TOML_CONTENT="+base64.StdEncoding.EncodeToString([]byte(content)))
		} else {
			log.Printf(config.ColorYellow+"warning: could not generate pyproject.toml from merged lock: %v"+config.ColorReset, err)
		}
	}

	// Artifact source credentials (private Galaxy / git repos inside container)
	for _, cred := range cfg.ArtifactSources {
		key := sanitizeEnvKey(cred.Name)
		if cred.Username != "" {
			args = append(args,
				"-e", fmt.Sprintf("%s%s=%s", config.EnvGitUserPrefix, key, cred.Username),
				"-e", fmt.Sprintf("%s%s=%s", config.EnvGitPassPrefix, key, cred.Password),
			)
		}
		if cred.URL != "" {
			args = append(args, "-e", fmt.Sprintf("%s%s=%s", config.EnvGitURLPrefix, key, cred.URL))
		}
		if cred.Token != "" {
			args = append(args, "-e", fmt.Sprintf("TOKEN_%s=%s", key, cred.Token))
		}
	}

	// --- Image ---
	args = append(args, image)

	// --- Container command ---
	// A shell one-liner that installs deps then runs the playbook.
	// All paths are container-internal; nothing touches the host file system.
	playbookCmd := buildContainerCommand(cfg)
	args = append(args, "sh", "-c", playbookCmd)

	return args, nil
}

// buildContainerCommand returns the shell command executed inside the container.
// It runs ansible-galaxy to install roles+collections into /tmp/diffusion/,
// then runs ansible-playbook from that isolated environment.
func buildContainerCommand(cfg DeployContainerConfig) string {
	rolesPath := containerRolesPath
	colsPath := containerCollectionsPath

	// Step 1: create install directories
	mkdirs := fmt.Sprintf("mkdir -p %s %s", rolesPath, colsPath)

	// Step 2: install roles from requirements.yml (if any roles present)
	installRoles := fmt.Sprintf(
		"ansible-galaxy role install -r /deploy/playbook/requirements.yml -p %s --no-deps 2>/dev/null || true",
		rolesPath,
	)

	// Step 3: install collections from requirements.yml (if any collections present)
	installCols := fmt.Sprintf(
		"ansible-galaxy collection install -r /deploy/playbook/requirements.yml -p %s 2>/dev/null || true",
		colsPath,
	)

	// Step 4: decode base64 SSH keys inside container (if provided via env vars).
	decodeKeyCmd := ""
	privateKeyFlag := ""
	if len(cfg.SSHKeys) > 0 {
		var decodeSteps []string
		decodeSteps = append(decodeSteps, "mkdir -p /tmp/ssh-keys")
		for host := range cfg.SSHKeys {
			envName := "SSH_KEY_" + strings.ToUpper(strings.NewReplacer("-", "_", ".", "_").Replace(host))
			keyPath := "/tmp/ssh-keys/" + host
			decodeSteps = append(decodeSteps,
				fmt.Sprintf("echo \"$%s\" | base64 -d > %s && chmod 600 %s", envName, keyPath, keyPath))
		}
		decodeKeyCmd = strings.Join(decodeSteps, " && ") + " && "

		// If there's a wildcard key "*", use --private-key globally.
		if _, hasWildcard := cfg.SSHKeys["*"]; hasWildcard && len(cfg.SSHKeys) == 1 {
			privateKeyFlag = " --private-key /tmp/ssh-keys/*"
		}
	}

	// Step 5: rewrite SSH key paths in the inventory if extra key dirs are mounted
	// or per-host SSH keys need ansible_ssh_private_key_file injected.
	inventoryFile := "/deploy/inventory.yml"
	extraDirs := extractSSHKeyDirs(cfg.InventoryPath)
	rewriteCmd := ""

	// Determine if we need per-host key injection (non-wildcard SSH keys).
	perHostKeys := make(map[string]string)
	for host, _ := range cfg.SSHKeys {
		if host != "*" {
			perHostKeys[host] = "/tmp/ssh-keys/" + host
		}
	}

	needsRewrite := len(extraDirs) > 0 || len(perHostKeys) > 0
	if needsRewrite {
		inventoryFile = "/tmp/inventory-rewritten.yml"
		var builder strings.Builder

		// Rewrite mounted extra SSH key dirs.
		for i, dir := range extraDirs {
			containerPath := fmt.Sprintf("/deploy/ssh-keys-%d", i)
			hostEscaped := strings.ReplaceAll(dir, "/", "\\/")
			containerEscaped := strings.ReplaceAll(containerPath, "/", "\\/")
			fmt.Fprintf(&builder, "s/%s/%s/g;", hostEscaped, containerEscaped)
			hostWinEscaped := strings.ReplaceAll(strings.ReplaceAll(dir, "\\", "/"), "/", "\\/")
			if hostWinEscaped != hostEscaped {
				fmt.Fprintf(&builder, "s/%s/%s/g;", hostWinEscaped, containerEscaped)
			}
		}

		sedExpr := builder.String()
		if sedExpr != "" {
			rewriteCmd = fmt.Sprintf("sed '%s' /deploy/inventory.yml > %s", sedExpr, inventoryFile)
		} else {
			rewriteCmd = fmt.Sprintf("cp /deploy/inventory.yml %s", inventoryFile)
		}

		// For per-host keys, use sed to inject ansible_ssh_private_key_file after the host line.
		for host, keyPath := range perHostKeys {
			// Insert ansible_ssh_private_key_file on the line after the hostname entry.
			escapedKeyPath := strings.ReplaceAll(keyPath, "/", "\\/")
			rewriteCmd += fmt.Sprintf(
				" && sed -i '/%s:/a\\      ansible_ssh_private_key_file: %s' %s",
				host, escapedKeyPath, inventoryFile)
		}
		rewriteCmd += " && "
	}

	// Step 6: run ansible-playbook with the wrapper
	playbookArgs := fmt.Sprintf(
		"ANSIBLE_ROLES_PATH=%s ANSIBLE_COLLECTIONS_PATH=%s ansible-playbook -i %s /deploy/playbook/wrapper.yml",
		rolesPath, colsPath, inventoryFile,
	)
	if cfg.ExtraVarsFile != "" {
		playbookArgs += " --extra-vars @/deploy/extra_vars.json"
	}
	playbookArgs += privateKeyFlag

	return fmt.Sprintf("set -e && %s && %s && %s && %s%s%s",
		mkdirs, installRoles, installCols, decodeKeyCmd, rewriteCmd, playbookArgs)
}

// buildPyprojectFromLock generates pyproject.toml content from a merged lock.
// Delegates to the existing dependency.GeneratePyProjectContent.
func buildPyprojectFromLock(lf *dependency.LockFile) (string, error) {
	collections := make([]config.CollectionRequirement, 0, len(lf.Collections))
	for _, c := range lf.Collections {
		collections = append(collections, config.CollectionRequirement{
			Name:      c.Name,
			Namespace: c.Namespace,
			Version:   c.ResolvedVersion,
		})
	}
	toolVersions := make(map[string]string)
	for _, t := range lf.Tools {
		toolVersions[t.Name] = t.ResolvedVersion
	}
	return dependency.GeneratePyProjectContent(collections, toolVersions, lf.Python)
}

// stripScenarioPrefix removes the "scenario." prefix from a name string.
func stripScenarioPrefix(name string) string {
	if parts := splitDot(name); len(parts) == 2 {
		return parts[1]
	}
	return name
}

func splitDot(s string) []string {
	for i, c := range s {
		if c == '.' {
			return []string{s[:i], s[i+1:]}
		}
	}
	return []string{s}
}
