package deploy

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// playbookPlay is a single play in the generated playbook YAML.
type playbookPlay struct {
	Name        string            `yaml:"name"`
	Hosts       string            `yaml:"hosts"`
	GatherFacts bool              `yaml:"gather_facts"`
	Vars        map[string]string `yaml:"vars,omitempty"`
	Roles       []playbookRole    `yaml:"roles"`
}

// playbookRole is the role entry inside a play's roles list.
type playbookRole struct {
	Role string `yaml:"role"`
}

// GeneratePlaybook builds a complete Ansible playbook from the provided role
// sources. Roles are grouped by their ApplyTo pattern so each unique hosts
// target becomes a single play, keeping the playbook compact.
//
// If a user-supplied playbook path is given (non-empty), this function is NOT
// called — the user's file is used as-is inside the container.
//
// Generated structure example:
//
//	---
//	# Auto-generated by diffusion deploy
//
//	- name: "diffusion deploy | all"
//	  hosts: all
//	  gather_facts: true
//	  roles:
//	    - role: geerlingguy.docker
//	    - role: myorg.common
//
//	- name: "diffusion deploy | webservers"
//	  hosts: webservers
//	  gather_facts: true
//	  roles:
//	    - role: myorg.app
func GeneratePlaybook(sources []RoleSource) ([]byte, error) {
	if len(sources) == 0 {
		return nil, fmt.Errorf("no role sources provided — cannot generate playbook")
	}

	// Group roles by their ApplyTo pattern preserving insertion order.
	type group struct {
		hosts string
		roles []string
	}
	var order []string
	groups := make(map[string]*group)

	for _, src := range sources {
		hosts := src.EffectiveApplyTo()
		name := src.EffectiveName()

		if _, exists := groups[hosts]; !exists {
			order = append(order, hosts)
			groups[hosts] = &group{hosts: hosts}
		}
		groups[hosts].roles = append(groups[hosts].roles, name)
	}

	var plays []playbookPlay
	for _, hosts := range order {
		g := groups[hosts]
		play := playbookPlay{
			Name:        fmt.Sprintf("diffusion deploy | %s", hosts),
			Hosts:       hosts,
			GatherFacts: true,
		}
		for _, r := range g.roles {
			play.Roles = append(play.Roles, playbookRole{Role: r})
		}
		plays = append(plays, play)
	}

	data, err := yaml.Marshal(plays)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal generated playbook: %w", err)
	}

	header := "---\n# Auto-generated by diffusion deploy — do not edit.\n# Roles are applied per host group as configured in role_sources.\n\n"
	return append([]byte(header), data...), nil
}

// roleBaseName extracts the short role name from a fully qualified Galaxy name
// or a git URL basename, for use in play names only.
func roleBaseName(name string) string {
	// For "namespace.role_name" keep the full name for unambiguous references.
	// For a bare git-derived name, just return it.
	parts := strings.SplitN(name, ".", 2)
	if len(parts) == 2 {
		return parts[1]
	}
	return name
}
