package deploy

import (
	"fmt"
	"strings"

	"diffusion/internal/dependency"

	"gopkg.in/yaml.v3"
)

// requirementsRole is the YAML structure for a role in requirements.yml.
type requirementsRole struct {
	Name    string `yaml:"name"`
	Src     string `yaml:"src,omitempty"`
	Scm     string `yaml:"scm,omitempty"`
	Version string `yaml:"version"`
}

// requirementsCollection is the YAML structure for a collection in requirements.yml.
type requirementsCollection struct {
	Name    string `yaml:"name"`
	Version string `yaml:"version,omitempty"`
	Source  string `yaml:"source,omitempty"`
}

// requirementsFile mirrors the standard Ansible requirements.yml format.
type requirementsFile struct {
	Roles       []requirementsRole       `yaml:"roles,omitempty"`
	Collections []requirementsCollection `yaml:"collections,omitempty"`
}

// GenerateRequirements produces a valid Ansible requirements.yml from a merged
// lock file. The file is used inside the container to install all roles and
// collections via ansible-galaxy before running the playbook.
//
// Version pinning: resolved_version is used when available so the container
// always installs the exact version resolved at lock-merge time.
func GenerateRequirements(lock *dependency.LockFile) ([]byte, error) {
	if lock == nil {
		return []byte("---\n"), nil
	}

	rf := requirementsFile{}

	for _, entry := range lock.Roles {
		name := stripScenarioPrefix(entry.Name)
		version := entry.ResolvedVersion
		if version == "" {
			version = entry.Version
		}

		role := requirementsRole{
			Version: version,
		}

		if entry.Source == "git" || entry.Src != "" {
			// Git role: src is the URL, name is optional override.
			role.Src = entry.Src
			role.Scm = "git"
			if entry.Namespace != "" {
				role.Name = entry.Namespace + "." + name
			} else {
				role.Name = name
			}
		} else {
			// Galaxy role: name is "namespace.rolename".
			role.Name = galaxyRoleName(entry.Namespace, name)
		}

		rf.Roles = append(rf.Roles, role)
	}

	for _, entry := range lock.Collections {
		name := stripScenarioPrefix(entry.Name)
		version := entry.ResolvedVersion
		if version == "" {
			version = entry.Version
		}

		col := requirementsCollection{
			Name:    collectionFQCN(entry.Namespace, name),
			Version: version,
		}
		// Custom source URL (private Galaxy server).
		if entry.Src != "" {
			col.Source = entry.Src
		}

		rf.Collections = append(rf.Collections, col)
	}

	// Always emit the top-level keys so ansible-galaxy doesn't error on empty.
	if len(rf.Roles) == 0 {
		rf.Roles = nil
	}
	if len(rf.Collections) == 0 {
		rf.Collections = nil
	}

	// Prepend a YAML header comment.
	data, err := yaml.Marshal(rf)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal requirements.yml: %w", err)
	}

	header := "---\n# Auto-generated by diffusion deploy — do not edit.\n\n"
	return append([]byte(header), data...), nil
}

func galaxyRoleName(namespace, name string) string {
	if namespace == "" {
		return name
	}
	return namespace + "." + name
}

func collectionFQCN(namespace, name string) string {
	if namespace == "" {
		return name
	}
	// Strip any remaining scenario prefix that slipped through.
	if idx := strings.Index(name, "."); idx >= 0 {
		name = name[idx+1:]
	}
	return namespace + "." + name
}
