package deploy

import (
	"fmt"
	"strings"

	"diffusion/internal/dependency"

	"gopkg.in/yaml.v3"
)

// requirementsRole is the YAML structure for a role in requirements.yml.
type requirementsRole struct {
	Name    string `yaml:"name"`
	Src     string `yaml:"src,omitempty"`
	Scm     string `yaml:"scm,omitempty"`
	Version string `yaml:"version"`
}

// requirementsCollection is the YAML structure for a collection in requirements.yml.
type requirementsCollection struct {
	Name    string `yaml:"name"`
	Version string `yaml:"version,omitempty"`
	Source  string `yaml:"source,omitempty"`
}

// requirementsFile mirrors the standard Ansible requirements.yml format.
type requirementsFile struct {
	Roles       []requirementsRole       `yaml:"roles,omitempty"`
	Collections []requirementsCollection `yaml:"collections,omitempty"`
}

// GenerateRequirements produces a valid Ansible requirements.yml from a merged
// lock file and the role sources. The file is used inside the container to
// install all roles and collections via ansible-galaxy before running the playbook.
//
// Role sources themselves are included first (these are the "main" roles being
// deployed), followed by their locked dependencies.
//
// Version pinning: resolved_version is used when available so the container
// always installs the exact version resolved at lock-merge time.
func GenerateRequirements(lock *dependency.LockFile, sources ...RoleSource) ([]byte, error) {
	rf := requirementsFile{}

	// Add the role sources themselves — these are the main roles being deployed.
	for _, src := range sources {
		role := requirementsRole{
			Version: src.Version,
		}
		switch strings.ToLower(src.SCM) {
		case "git":
			role.Src = src.URL
			role.Scm = "git"
			role.Name = src.EffectiveName()
		case "galaxy":
			role.Name = src.Galaxy
		default:
			continue
		}
		rf.Roles = append(rf.Roles, role)
	}

	if lock == nil {
		// No lock file — only role sources.
		if len(rf.Roles) == 0 {
			return []byte("---\n"), nil
		}
	} else {
		// Add locked dependency roles.
		for _, entry := range lock.Roles {
			name := stripScenarioPrefix(entry.Name)
			version := entry.ResolvedVersion
			if version == "" {
				version = entry.Version
			}

			role := requirementsRole{
				Version: version,
			}

			if entry.Source == "git" || entry.Src != "" {
				role.Src = entry.Src
				role.Scm = "git"
				// Use the bare role name (without namespace) for git-sourced roles.
				// Parent roles reference dependencies by their plain name (e.g.
				// "docker_rootless"), not by "namespace.docker_rootless", so the
				// install directory name must match what include_role expects.
				role.Name = name
			} else {
				role.Name = galaxyRoleName(entry.Namespace, name)
			}

			// Skip if already added as a role source (avoid duplicates).
			if isDuplicateRole(rf.Roles, role) {
				continue
			}

			rf.Roles = append(rf.Roles, role)
		}

		// Add locked dependency collections.
		for _, entry := range lock.Collections {
			name := stripScenarioPrefix(entry.Name)
			version := entry.ResolvedVersion
			if version == "" {
				version = entry.Version
			}

			col := requirementsCollection{
				Name:    collectionFQCN(entry.Namespace, name),
				Version: version,
			}
			if entry.Src != "" {
				col.Source = entry.Src
			}

			rf.Collections = append(rf.Collections, col)
		}
	}

	// Always emit the top-level keys so ansible-galaxy doesn't error on empty.
	if len(rf.Roles) == 0 {
		rf.Roles = nil
	}
	if len(rf.Collections) == 0 {
		rf.Collections = nil
	}

	// Prepend a YAML header comment.
	data, err := yaml.Marshal(rf)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal requirements.yml: %w", err)
	}

	header := "---\n# Auto-generated by diffusion deploy — do not edit.\n\n"
	return append([]byte(header), data...), nil
}

// isDuplicateRole checks if a role with the same name or src already exists in the list.
func isDuplicateRole(roles []requirementsRole, candidate requirementsRole) bool {
	for _, r := range roles {
		if r.Name == candidate.Name {
			return true
		}
		if r.Src != "" && r.Src == candidate.Src {
			return true
		}
	}
	return false
}

func galaxyRoleName(namespace, name string) string {
	if namespace == "" {
		return name
	}
	return namespace + "." + name
}

func collectionFQCN(namespace, name string) string {
	if namespace == "" {
		return name
	}
	// Strip any remaining scenario prefix that slipped through.
	if idx := strings.Index(name, "."); idx >= 0 {
		name = name[idx+1:]
	}
	return namespace + "." + name
}
