package deploy

import (
	"bytes"
	"fmt"
	"text/template"
	"time"
)

// WrapperConfig holds the parameters for the generated wrapper playbook.
type WrapperConfig struct {
	// UserPlaybook is the path to the user's playbook inside the container
	// (e.g. "/deploy/playbook/site.yml").
	UserPlaybook string
	// SkipIfSucceededFor is the period within which a successful prior run
	// may be skipped. 0 means never skip.
	SkipIfSucceededFor time.Duration
	// RunID is a stable hash of all deploy inputs. Used to detect whether the
	// last run was for the same inputs.
	RunID string
	// DiffusionVersion is embedded into the state file for diagnostics.
	DiffusionVersion string
}

// GenerateWrapperPlaybook returns the YAML bytes for a wrapper playbook that:
//  1. Reads ~/.diffusion/state on every remote host.
//  2. Skips the user playbook if the last run succeeded within SkipIfSucceededFor
//     AND used the same RunID (i.e. identical inputs).
//  3. Imports the user's playbook.
//  4. Writes a new ~/.diffusion/state entry on success.
//  5. Writes status:"failed" to ~/.diffusion/state on failure.
func GenerateWrapperPlaybook(cfg WrapperConfig) ([]byte, error) {
	skipSeconds := int64(cfg.SkipIfSucceededFor.Seconds())

	data := struct {
		UserPlaybook     string
		RunID            string
		DiffusionVersion string
		SkipSeconds      int64
		SkipEnabled      bool
	}{
		UserPlaybook:     cfg.UserPlaybook,
		RunID:            cfg.RunID,
		DiffusionVersion: cfg.DiffusionVersion,
		SkipSeconds:      skipSeconds,
		SkipEnabled:      skipSeconds > 0,
	}

	tmpl, err := template.New("wrapper").Parse(wrapperPlaybookTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse wrapper playbook template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("failed to render wrapper playbook: %w", err)
	}

	return buf.Bytes(), nil
}

// wrapperPlaybookTemplate is the Go text/template for the generated wrapper.
// It uses three plays:
//   - Play 1: Read remote state and decide whether to skip.
//   - Play 2: Import the user's playbook (skipped when diffusion_skip is true).
//   - Play 3: Write success state (skipped on skip or failure).
//   - Rescue in play 2 writes failure state and re-raises.
const wrapperPlaybookTemplate = `---
# AUTO-GENERATED by diffusion deploy — do not edit.
# RunID: {{ .RunID }}

- name: "diffusion deploy | state check"
  hosts: all
  gather_facts: true
  tasks:
    - name: "Ensure ~/.diffusion directory exists"
      ansible.builtin.file:
        path: "~/.diffusion"
        state: directory
        mode: "0700"

    - name: "Read remote diffusion state"
      ansible.builtin.slurp:
        src: "~/.diffusion/state"
      register: _diffusion_state_raw
      ignore_errors: true

    - name: "Parse remote diffusion state"
      ansible.builtin.set_fact:
        _diffusion_state: "{{ '{{' }} _diffusion_state_raw.content | b64decode | from_yaml {{ '}}' }}"
      when: _diffusion_state_raw is not failed

{{ if .SkipEnabled }}
    - name: "Evaluate skip condition"
      ansible.builtin.set_fact:
        diffusion_skip: >-
          {{ '{{' }}
            (_diffusion_state is defined)
            and (_diffusion_state.status | default('') == 'success')
            and (_diffusion_state.run_id | default('') == '{{ .RunID }}')
            and ((ansible_date_time.epoch | int) - (_diffusion_state.last_epoch | default('0') | int) < {{ .SkipSeconds }})
          {{ '}}' }}

    - name: "Skip notice"
      ansible.builtin.debug:
        msg: >-
          Skipping deploy — last successful run with identical inputs was within
          the configured skip period ({{ .SkipSeconds }}s). Set skip_if_succeeded_within=0
          to force re-deployment.
      when: diffusion_skip | default(false)
{{ else }}
    - name: "Skip disabled"
      ansible.builtin.set_fact:
        diffusion_skip: false
{{ end }}

- name: "diffusion deploy | user playbook"
  import_playbook: "{{ .UserPlaybook }}"
  when: not (diffusion_skip | default(false))

- name: "diffusion deploy | write success state"
  hosts: all
  gather_facts: true
  tasks:
    - name: "Write diffusion state (success)"
      ansible.builtin.copy:
        dest: "~/.diffusion/state"
        content: |
          last_run: "{{ '{{' }} ansible_date_time.iso8601 {{ '}}' }}"
          last_epoch: "{{ '{{' }} ansible_date_time.epoch {{ '}}' }}"
          status: "success"
          run_id: "{{ .RunID }}"
          diffusion_version: "{{ .DiffusionVersion }}"
          playbook: "{{ .UserPlaybook }}"
        mode: "0600"
      when: not (diffusion_skip | default(false))
`

// Note: failure state is written by a rescue play that must be appended when
// GenerateWrapperPlaybook is used inside a block/rescue. For simplicity at this
// stage the container.go caller wraps the ansible-playbook invocation and writes
// a minimal failure state via an ad-hoc command if the exit code is non-zero.
